// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnQGO4HkgCqAhkLOqCI7WX5QG1LY9Ly2w',
    appId: '1:48069298147:web:5394db2ee5a3384e4102d6',
    messagingSenderId: '48069298147',
    projectId: 'financeflow-app',
    authDomain: 'financeflow-app.firebaseapp.com',
    storageBucket: 'financeflow-app.firebasestorage.app',
    measurementId: 'G-ZZCTRM5F0R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-3OaKIlsck_RnWxFmFbj1BrdgbMLF_tM',
    appId: '1:48069298147:android:9efb124878c333c94102d6',
    messagingSenderId: '48069298147',
    projectId: 'financeflow-app',
    storageBucket: 'financeflow-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1H3DugEKtC0EmiiPUjyWsQ7V6gUvXcM4',
    appId: '1:48069298147:ios:4e3adba725e150f44102d6',
    messagingSenderId: '48069298147',
    projectId: 'financeflow-app',
    storageBucket: 'financeflow-app.firebasestorage.app',
    iosBundleId: 'com.example.financeflowApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1H3DugEKtC0EmiiPUjyWsQ7V6gUvXcM4',
    appId: '1:48069298147:ios:4e3adba725e150f44102d6',
    messagingSenderId: '48069298147',
    projectId: 'financeflow-app',
    storageBucket: 'financeflow-app.firebasestorage.app',
    iosBundleId: 'com.example.financeflowApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnQGO4HkgCqAhkLOqCI7WX5QG1LY9Ly2w',
    appId: '1:48069298147:web:aac630bcd41de6d84102d6',
    messagingSenderId: '48069298147',
    projectId: 'financeflow-app',
    authDomain: 'financeflow-app.firebaseapp.com',
    storageBucket: 'financeflow-app.firebasestorage.app',
    measurementId: 'G-QXDRQT43TP',
  );
}
